# fly.toml app configuration file generated for restore-tezzz on 2023-10-02T11:15:55+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restore-tezzz"
primary_region = "waw"

[build]
  image = "thezzz/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51NwMBzFdEeNUxE0gCgMQJOdohrrkNCrcYTA4m3gkV6DabXXNuXXAbexxgyDdJ2ppZXdKzoKLL8LVnDSg4BvIcMYf00e8LCA16m"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
